export const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 80,
      countInStock: 8,
      brand: 'Adidas',
      rating: 1,
      numReviews: 9,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 300,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 2,
      description: 'high quality Product',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 100,
      countInStock: 3,
      brand: 'Nike',
      rating: 3,
      numReviews: 15,
      description: 'high quality Product',
    },
  ],
};
